### PR TITLE
mongo + dgraph stores

### PR DESCRIPTION
**Pull request by bh90210**
Hey there,

I hope what I've done is not redundant but I was in need of dgraph and mongo store implementations so I made them.

there are few details that I would like feedback on but the most important one is the comment I found on bolt's store
```go
// Author's notes:
// expiration is handled by the session manager for the whole session, so the `db.Destroy` will be called when and if needed.
// Therefore we don't have to implement a TTL here, but we need a `db.Cleanup`, as we did previously, method to delete any expired if server restarted
// (badger does not need a `Cleanup` because we set the TTL based on the lifetime.DurationUntilExpiration()).
```

Dgraph does not support TTL so I opted to not use it with mongo either. If I understand correctly I should also implement a clean-up function too
```go
// Cleanup removes any invalid(have expired) session entries on initialization.
```
and call it on each initialisation of a New DB ?

Thanks!

### CODE REVIEW

**Comment by bh90210** [comment]
@kataras sorry to bother u BUT should I maybe make a PR @ iris repo?
in any case I have been testing without the `cleanup()` helper and it works fine but any feedback will be greatly appreciated :)

**Comment by kataras** [comment]
Hello @bh90210,

Sorry for the delayed response. 

The code looks good, good job here. To answer your question no, this repository will remain as it is (it has support for fasthttp and net/http too. Iris sessions manager is similar though).

My only concern is that, this PR adds 3 **huge/big file size dependencies**:

1. `"go.mongodb.org/mongo-driver/mongo"`
2. `"google.golang.org/grpc"`
3. `"github.com/dgraph-io/dgo"` 

It will make it slower to install the package for new users if we merge it right now.

Based on that, I am not sure if those new databases should live in Iris/or this repository itself (which already contains some dependecies as well). My proposal is to let you create a new repository (or add you to the [iris-contrib](https://github.com/iris-contrib) github organisation) and whenever you have time you can create a repository and implement the mongo and dgraph sessions databases for Iris/or/and go-sessions there instead. Just keep in mind that in Iris you may need to do some changes based on its Database interface.

However, I am willing to merge it here if you don't like the idea of a separate repository. Your work is excellent here and I don't want to leave our users without dgraph and mongo support when they can have it.

Happy new year 🎅🏽 🤶🏽 
Gerasimos Maropoulos

**Comment by bh90210** [comment]
Καλημέρα Γεράσιμε, καλή χρονιά!

uh to be honest I was in a hurry so I did the ugly thing to create a new branch off the forked repo and very very fast proceeded continue working. I didn't sit back to think anything else! So honestly I will do the next ugly thing and let *you* decide what to happen :-p 

The way I did it with gorilla sessions was to have a repo with all the implementations under my username and that worked fine (for me at least) https://github.com/bh90210/vagorillasessionsstores 

Any and all solutions I am in! I'm in if you'd prefer to create a couple of repositories in iris-contrib (to cover both go-session and iris interfaces- I am absolutely fine to re-implement for iris interface btw), I'm in if you'd prefer to have a separate repo under my username, or at the end of the day merge it here..

grpc, dgo and mongo driver are indeed huge dependencies and since the `db interface` exists for this reason I have no issue to drop this merge. 

From the user perspective just a link from go-session/iris docs to the implementations (wherever they live) and a decent README along them so everything goes smoothly, is fine!

**Comment by kataras** [comment]
Good morning @bh90210 and thanks for that greek tone I really appreciate it 🤗

You did well opening a PR here, PRs are fine for discussion too :)

### About the cleanup method on boltdb:

There is not a requirement by the Database interface. At general: when the back storage has its own TTL feature that you use in the database implementation then the data/session key-values will be automatically removed after they expired, you don't need to implement it but if the database implementation stores expire times manually (e.g. in a prefixed key or inside the session object itself) then somehow the expired entries must be deleted at some point to free the file size/ or memory in the back storage, we can do that (depending on the cost): by running a "cleanup" every a customized "X" time or cleanup once on its initialization if the back storage can handle a large amount of data without issues, like boltdb does or/and export that cleanup functionality for end-developers use too (although a global database lock will be required at 2nd and 3rd options). A good idea of the 2nd option (run a "gc/cleanup" every "x" time) is implemented by another project of mine that you can borrow/motivated too: https://github.com/kataras/jwt/blob/main/blocklist.go

### About the implementations hosting:

Let's start by how they will be organized, you think all those drivers should live in the same repository? We/you can split them for faster downloads. My opinion is no; At first I believed different github repositories for each driver(mongo,dgraph,grpc) will be better option but we must take care of the go import paths e.g. github.com/.../sessiondb-mongo, github.com/.../sessiondb-grpc, github.com/.../sessiondb-dgraph -- don't look nice to my eyes, therefore we can host all contributions to the same repository e.g. `github.com/bh90210/sessiondb` which will contain the three folders (implementations) for go-sessions. The examples will always be linked with the main go-sessions and Iris docs (and e-book) for easier user/end-developer discovery. I have two proposals:

1. Move go-sessions implementations and future iris/sessiondb implementations under your own github username
2. Move go-sessions implementation to your github username and host the iris/sessiondb ones at the [iris-contrib](https://github.com/iris-contrib) organisation.

I think the 2nd option is easier to follow up because we don't need a github organisation just for the go-sessions project, but Iris has an organisation for that type of things already. 

I've created the https://github.com/iris-contrib/sessiondb repository and invited you as Admin (so you can push whenever you have time).

And of course, on both projects (go-sessions and iris/sessiondb), the implementations should be documented exactly like the builtin session database implementation do.


Waiting for your response!

**Comment by kataras** [comment]
Good morning @bh90210 and thanks for that greek tone I really appreciate it 🤗

You did well opening a PR here, PRs are fine for discussion too :)

### About the cleanup method on boltdb:

There is not a requirement by the Database interface. At general: when the back storage has its own TTL feature that you use in the database implementation then the data/session key-values will be automatically removed after they expired, you don't need to implement it but if the database implementation stores expire times manually (e.g. in a prefixed key or inside the session object itself) then somehow the expired entries must be deleted at some point to free the file size/ or memory in the back storage, we can do that (depending on the cost): by running a "cleanup" every a customized "X" time or cleanup once on its initialization if the back storage can handle a large amount of data without issues, like boltdb does or/and export that cleanup functionality for end-developers use too (although a global database lock will be required at 2nd and 3rd options). A good idea of the 2nd option (run a "gc/cleanup" every "x" time) is implemented by another project of mine that you can borrow/motivated too: https://github.com/kataras/jwt/blob/main/blocklist.go

### About the implementations hosting:

Let's start by how they will be organized, you think all those drivers should live in the same repository? We/you can split them for faster downloads. My opinion is no; At first I believed different github repositories for each driver(mongo,dgraph,grpc) will be better option but we must take care of the go import paths e.g. github.com/.../sessiondb-mongo, github.com/.../sessiondb-grpc, github.com/.../sessiondb-dgraph -- don't look nice to my eyes, therefore we can host all contributions to the same repository e.g. `github.com/bh90210/sessiondb` which will contain the three folders (implementations) for go-sessions. The examples will always be linked with the main go-sessions and Iris docs (and e-book) for easier user/end-developer discovery. I have two proposals:

1. Move go-sessions implementations and future iris/sessiondb implementations under your own github username
2. Move go-sessions implementation to your github username and host the iris/sessiondb ones at the [iris-contrib](https://github.com/iris-contrib) organisation.

I think the 2nd option is easier to follow up because we don't need a github organisation just for the go-sessions project, but Iris has an organisation for that type of things already. 

I've created the https://github.com/iris-contrib/sessiondb repository and invited you as Admin (so you can push whenever you have time).

And  of course for the  database implementations of both projects (go-sessions and iris/sessiondb), the implementations should be documented exactly like the builtin session database implementations do.


Waiting for your response!

**Comment by kataras** [comment]
@bh90210 Good morning and happy new year Χρήστο! Thanks for that greek tone I really appreciate it 🤗

You did well opening a PR here, PRs are fine for discussion too :)

### About the cleanup method on boltdb:

There is not a requirement by the Database interface. At general: when the back storage has its own TTL feature that you use in the database implementation then the data/session key-values will be automatically removed after they expired, you don't need to implement it but if the database implementation stores expire times manually (e.g. in a prefixed key or inside the session object itself) then somehow the expired entries must be deleted at some point to free the file size/ or memory in the back storage, we can do that (depending on the cost): by running a "cleanup" every a customized "X" time or cleanup once on its initialization if the back storage can handle a large amount of data without issues, like boltdb does or/and export that cleanup functionality for end-developers use too (although a global database lock will be required at 2nd and 3rd options). A good idea of the 2nd option (run a "gc/cleanup" every "x" time) is implemented by another project of mine that you can borrow/motivated too: https://github.com/kataras/jwt/blob/main/blocklist.go

### About the implementations hosting:

Let's start by how they will be organized, you think all those drivers should live in the same repository? We/you can split them for faster downloads. My opinion is no; At first I believed different github repositories for each driver(mongo,dgraph,grpc) will be better option but we must take care of the go import paths e.g. github.com/.../sessiondb-mongo, github.com/.../sessiondb-grpc, github.com/.../sessiondb-dgraph -- don't look nice to my eyes, therefore we can host all contributions to the same repository e.g. `github.com/bh90210/sessiondb` which will contain the three folders (implementations) for go-sessions. The examples will always be linked with the main go-sessions and Iris docs (and e-book) for easier user/end-developer discovery. I have two proposals:

1. Move go-sessions implementations and future iris/sessiondb implementations under your own github username
2. Move go-sessions implementation to your github username and host the iris/sessiondb ones at the [iris-contrib](https://github.com/iris-contrib) organisation.

I think the 2nd option is easier to follow up because we don't need a github organisation just for the go-sessions project, but Iris has an organisation for that type of things already. 

I've created the https://github.com/iris-contrib/sessiondb repository and invited you as Admin (so you can push whenever you have time).

And  of course for the  database implementations of both projects (go-sessions and iris/sessiondb), the implementations should be documented exactly like the builtin session database implementations do.


Waiting for your response!

**Comment by bh90210** [comment]
hey! 

for `go-sessions` something like that?
https://github.com/bh90210/go-sessions-stores
and have each store under it's own directory?
I could also try the `go submodules` technique that I always wanted to but never really got a use case for https://github.com/go-modules-by-example/index/tree/master/009_submodules
so as to accomplish a level of independence of one package/store from the other even though they will exist in the same repo/branch. (each store will have it's unique go.mod and git version/tag)

for `iris/sessiondb` I have already accepted the invitation so yes the solution is fine! I will have to look at the interface as I haven't yet and slowly re-implement everything but via the PR method though, just so more eyes can see that everything is OK before uploading anything. But just to be sure that we are on the same page, on this repo we will just uploading the iris interface implementations, right?

also I am sure u'll have no issue with this but please excuse me as things will move slowly as I'm unusually busy lately.

Have a great day! (it's 4 in the morning tho! :smile:)

ps. I am actually greek, I just opt to default write in english on public facing issues.
ps2. many people get confused but my first name is Byron :)

**Comment by bh90210** [comment]
Hello there @kataras 

I have finished the `go-sessions` part of the plan, I will now work on the iris interface implementation.

Please check it out here https://github.com/bh90210/go-sessions-stores

The only change I have made for this PR is include the implementations in the docs.

Please advice :)

**Comment by bh90210** [comment]
and since I have you here please also check out the iris implementation 
https://github.com/iris-contrib/sessiondb

should work but I will more thoroughly test later today

**Pull request closed without merging**
